### ISSUE TITLE
Trying to run

### ISSUE THREAD

**Issue by Mooseman923** [snorpey/jpg-glitch#9]
Sorry I'm a code novice, so please forgive my ignorence. I'm trying to get to get this to run locally using Chrome or Waterfox. I can get it to load into Chrome and see the initial loading prompt, but then get a DNS_PROBE_FINISHED_NXDOMAIN error. When I try to load this into Waterfox, It will not load anything. Do you have any better suggestions for loading and running locally?  I love this script as well as your triangulation script. I use them often for my art and would love to use them running locally. Thanks!

**Comment by snorpey** [comment]
hey @Mooseman923 thank you for your interest in this project.

i don't have any experience with Waterfox, so I don't know if it is causing the issue.

however, i recommend using a local web server so that you can open the index file like this: ``http://localhost/jpg-glitch/index.html`` instead of ``file://jpg-glitch/index.html``.

in addition to that, it makes probably sense to comment out the [redirection to https](https://github.com/snorpey/jpg-glitch/blob/master/index.html#L56) on a local server  in the index.html file.
